@Library('erp-shared-library@main') _


erpPipeline(

    /*
     * AWS CONFIGURATION
     */

    accountId: '699975678958',

    awsRegion: 'us-east-1',


    /*
     * PROJECT CONFIGURATION
     */

    projectName: 'erp',

    pocName: 'Krishna',


    /*
     * JENKINS CREDENTIAL IDs
     */

    awsCredentials: 'aws-erp',

    gitCredentials: 'github-erp',

    dockerCredentials: 'dockerhub-credentials',

    appEc2Credentials: 'erp-app-ec2',


    /*
     * DOCKER CONFIGURATION
     */

    dockerRegistry: 'indiadelhi001',


    /*
     * APPLICATION REPOSITORY
     */

    applicationRepo: 'https://github.com/krishna-stackly/ERP.git',


    /*
     * ENVIRONMENT MAPPING
     *
     * Left side  = Jenkins parameter
     * Right side = Actual AWS EC2 tag value
     */

    environments: [

        'dev': 'dev',

        'qa': 'qa'

    ]

)