@Library('erp-shared-library@main') _

if (env.BRANCH_NAME != 'main') {

    echo """
==================================================
PIPELINE NOT EXECUTED
==================================================

Current Branch : ${env.BRANCH_NAME}
Allowed Branch : main

==================================================
"""

    currentBuild.result = 'NOT_BUILT'
    return
}


erpPipeline(

    accountId: '699975678958',

    awsRegion: 'us-east-1',

    projectName: 'erp',

    pocName: 'Krishna',

    awsCredentials: 'aws-erp',

    gitCredentials: 'github-erp',

    dockerCredentials: 'dockerhub-credentials',

    appEc2Credentials: 'erp-app-ec2',

    applicationRepo: 'https://github.com/krishna-stackly/ERP.git',

    environments: [

        'Dev': 'dev',

        'QA': 'qa'
    ]
)