/*

* ============================================================
* LOAD SHARED LIBRARY
*
* Always use the main branch of the shared library.
* ============================================================
  */

@Library('erp-shared-library@main') _

/*

* ============================================================
* BRANCH VALIDATION
*
* Execute the deployment pipeline only when this Jenkinsfile
* is running from the application's main branch.
* ============================================================
  */

if (env.BRANCH_NAME != 'main') {


echo """


==================================================
PIPELINE NOT EXECUTED
=====================

Current Branch : ${env.BRANCH_NAME}
Allowed Branch : main

This deployment pipeline runs only from the main branch.

==================================================
"""


currentBuild.result = 'NOT_BUILT'
return


}

/*

* ============================================================
* CALL ERP SHARED PIPELINE
*
* Static configuration is passed through the config map.
*
* VERSION and ENVIRONMENT are Jenkins build parameters
* created and consumed inside the shared library.
* ============================================================
  */

erpPipeline(


/*
 * ========================================================
 * AWS CONFIGURATION
 * ========================================================
 */

accountId: '699975678958',
awsRegion: 'us-east-1',


/*
 * ========================================================
 * TERRAFORM / INFRASTRUCTURE CONFIGURATION
 *
 * These values must exactly match the Terraform-created
 * resource tags.
 * ========================================================
 */

projectName: 'erp',
pocName: 'Krishna',


/*
 * ========================================================
 * JENKINS AWS CREDENTIAL
 *
 * Must exactly match the Credential ID configured
 * in Jenkins.
 * ========================================================
 */

awsCredentials: 'aws-erp',


/*
 * ========================================================
 * DEPLOYMENT ENVIRONMENTS
 *
 * These become the ENVIRONMENT Jenkins parameter options.
 *
 * They must match the Terraform Environment tag values.
 * ========================================================
 */

environments: [
    'Dev': 'Dev',
    'QA' : 'QA'
]


)
